### ISSUE TITLE
Q7: Tim create team contribution to MKD

### ISSUE THREAD

**Issue by brittweinstein** [openstax/domo#63]
![IMG_5549-1.jpg](https://images.zenhubusercontent.com/5a01faba8a75884b90866af7/63c47f1e-823a-488d-828a-340c2b5a9954)

**Comment by Tim-Reiland** [comment]
Cannot create large all encompassing dashboard item using all teams and all MKDs. Created card to be able to display change in MKD by team before and after an event

**Comment by brittweinstein** [comment]
@Tim-Reiland what is the specific issue with the all encompassing dash?? I'd like to discuss this on my call with Will today.

**Comment by Tim-Reiland** [comment]
![image](https://user-images.githubusercontent.com/47796689/54141819-6bbadb80-43f4-11e9-9e75-bdcd4deba47d.png)

**Comment by Tim-Reiland** [comment]
This is actually doable and will start working towards this. The problem was getting this data and comparing it over time (or even one period vs another)
