### ISSUE TITLE
GithHub/ZenHub to Domo export: add fields issue_created_at, issue_closed_at, pr_connected_issue_repo, pr_connected_issue_number

### ISSUE THREAD

**Issue by BruceP99166** [openstax/domo#70]
# Description
As a Project Manager I want additional information about issues: when created, when closed, whether a pr is connected to an issue: issue_created_at, issue_closed_at, pr_is_connected

# Acceptance
- Fields are added to the GitHub/ZenHub to Domo export: 
  - issue_created_at = datetime when issue was created
  - issue_closed_at = datetime when issue was closed.  Blank if issue is open.
  - pr_is_connected = True if pr is connected to an issue.

**Comment by brittweinstein** [comment]
@BruceP99166 please put points on this
