### ISSUE TITLE
Bruce implement reports based on metrics decided by Carly and Kim for OKR #3

### ISSUE THREAD

**Issue by brittweinstein** [openstax/domo#95]
# Description
Describe the desired change.

# Acceptance Criteria
Give criteria for acceptance.

# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else

**Comment by BruceP99166** [comment]
Superceded.
